
import React, { useState, useEffect } from 'react';
import { Card } from './Card';
import { Button } from './Button';
import { Input, TextArea } from './Input';
import { Select } from './Select';
import { VisualStyle, BookDetails, GenerationConfig, Language, Complexity, AspectRatio, SearchDepth, TextDensity } from '../types';
import { STYLES, LANGUAGES, COMPLEXITIES, FORMATS, SEARCH_DEPTHS, TEXT_DENSITIES } from '../constants';

interface ChildrenBookWizardProps {
  isOpen: boolean;
  onClose: () => void;
  onSubmit: (details: BookDetails, config: GenerationConfig, referenceImage?: string) => void;
}

export const ChildrenBookWizard: React.FC<ChildrenBookWizardProps> = ({ isOpen, onClose, onSubmit }) => {
  const [step, setStep] = useState(1);
  const [details, setDetails] = useState<BookDetails>({
    childName: '',
    age: 5,
    gender: '',
    preferences: '',
    hobbies: '',
    favoriteAnimal: '',
    biggestFear: '',
    hero: '',
    favoriteColor: '',
    activities: '',
    friends: '',
    favoritePlace: '',
    storyTone: 'Aventuros',
    length: 'Scurt (10 Pagini)',
    humorLevel: 5,
    emotionLevel: 5
  });

  // Configuration State with Defaults appropriate for Books
  const [selectedStyle, setSelectedStyle] = useState<VisualStyle>(VisualStyle.STORYBOOK);
  const [selectedLanguage, setSelectedLanguage] = useState<Language>(Language.RO);
  const [selectedFormat, setSelectedFormat] = useState<AspectRatio>(AspectRatio.SQUARE);
  const [selectedComplexity, setSelectedComplexity] = useState<Complexity>(Complexity.SIMPLE);
  const [selectedSearchDepth, setSelectedSearchDepth] = useState<SearchDepth>(SearchDepth.NONE);
  const [selectedTextDensity, setSelectedTextDensity] = useState<TextDensity>(TextDensity.BALANCED);
  
  const [uploadedImage, setUploadedImage] = useState<string | undefined>(undefined);

  // RESET STATE ON OPEN
  useEffect(() => {
    if (isOpen) {
        setStep(1);
        setUploadedImage(undefined);
        setDetails({
            childName: '',
            age: 5,
            gender: '',
            preferences: '',
            hobbies: '',
            favoriteAnimal: '',
            biggestFear: '',
            hero: '',
            favoriteColor: '',
            activities: '',
            friends: '',
            favoritePlace: '',
            storyTone: 'Aventuros',
            length: 'Scurt (10 Pagini)',
            humorLevel: 5,
            emotionLevel: 5
        });
        setSelectedStyle(VisualStyle.STORYBOOK);
        setSelectedLanguage(Language.RO);
        setSelectedFormat(AspectRatio.SQUARE);
    }
  }, [isOpen]);

  if (!isOpen) return null;

  const handleFileUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setUploadedImage(reader.result as string);
      };
      reader.readAsDataURL(file);
    }
  };

  const handleFinish = () => {
    const config: GenerationConfig = {
        topic: '', // Will be generated by App.tsx based on details
        language: selectedLanguage,
        style: selectedStyle,
        complexity: selectedComplexity,
        format: selectedFormat,
        searchDepth: selectedSearchDepth,
        textDensity: selectedTextDensity,
        uploadedReference: uploadedImage
    };
    onSubmit(details, config, uploadedImage);
    onClose();
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-slate-900/80 backdrop-blur-sm">
      <Card elevated className="w-full max-w-2xl max-h-[90vh] overflow-y-auto relative animate-fadeIn">
        <button 
          onClick={onClose} 
          className="absolute top-4 right-4 text-slate-400 hover:text-crail-500 transition-colors z-10 p-2"
          aria-label="Close"
        >
          <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>

        <div className="mb-6">
            <h2 className="font-serif text-3xl font-bold text-crail-600">Creator Cărți pentru Copii</h2>
            <p className="text-slate-500">Creează o poveste magică personalizată pentru un copil.</p>
        </div>

        {step === 1 && (
            <div className="space-y-4">
                <h3 className="font-bold text-lg text-slate-dark border-b pb-2">Pasul 1: Eroul</h3>
                <div className="grid grid-cols-2 gap-4">
                    <Input label="Numele Copilului" value={details.childName} onChange={e => setDetails({...details, childName: e.target.value})} />
                    <Input label="Vârstă" type="number" value={details.age} onChange={e => setDetails({...details, age: parseInt(e.target.value)})} />
                </div>
                <div className="grid grid-cols-2 gap-4">
                    <Input label="Gen" value={details.gender} onChange={e => setDetails({...details, gender: e.target.value})} />
                    <Input label="Culoare Preferată" value={details.favoriteColor} onChange={e => setDetails({...details, favoriteColor: e.target.value})} />
                </div>
                <Input label="Animal Preferat (Sidekick?)" value={details.favoriteAnimal} onChange={e => setDetails({...details, favoriteAnimal: e.target.value})} />
                <TextArea label="Hobby-uri & Interese" value={details.hobbies} onChange={e => setDetails({...details, hobbies: e.target.value})} placeholder="Dinozauri, Spațiu, Gătit..." />
                
                <div className="bg-ivory-medium p-4 rounded-lg border border-ivory-dark mt-4">
                    <label className="block font-serif text-sm font-bold text-slate-dark mb-2">Încarcă Poza Copilului (Pentru Design Personaj)</label>
                    <input type="file" onChange={handleFileUpload} className="block w-full text-sm text-slate-medium file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:bg-crail-50 file:text-crail-600 hover:file:bg-crail-100"/>
                    {uploadedImage && <p className="text-xs text-green-600 mt-1">✓ Poză Încărcată</p>}
                </div>

                <div className="flex justify-end pt-4">
                    <Button onClick={() => setStep(2)}>Următorul: Povestea &rarr;</Button>
                </div>
            </div>
        )}

        {step === 2 && (
            <div className="space-y-4">
                <h3 className="font-bold text-lg text-slate-dark border-b pb-2">Pasul 2: Povestea & Lumea</h3>
                <Input label="Tonul Poveștii" value={details.storyTone} onChange={e => setDetails({...details, storyTone: e.target.value})} placeholder="Magic, Educativ, Amuzant..." />
                <Input label="Cea mai mare frică (de învins)" value={details.biggestFear} onChange={e => setDetails({...details, biggestFear: e.target.value})} />
                <Input label="Erou Preferat" value={details.hero} onChange={e => setDetails({...details, hero: e.target.value})} />
                <TextArea label="Activități preferate" value={details.activities} onChange={e => setDetails({...details, activities: e.target.value})} />
                <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-2">
                        <label className="text-sm font-bold">Nivel Umor (1-10)</label>
                        <input type="range" min="1" max="10" value={details.humorLevel} onChange={e => setDetails({...details, humorLevel: parseInt(e.target.value)})} className="w-full accent-crail-500" />
                    </div>
                    <div className="space-y-2">
                        <label className="text-sm font-bold">Nivel Emoție (1-10)</label>
                        <input type="range" min="1" max="10" value={details.emotionLevel} onChange={e => setDetails({...details, emotionLevel: parseInt(e.target.value)})} className="w-full accent-crail-500" />
                    </div>
                </div>

                <div className="flex justify-between pt-4">
                    <Button variant="secondary" onClick={() => setStep(1)}>&larr; Înanpoi</Button>
                    <Button onClick={() => setStep(3)}>Următorul: Setări &rarr;</Button>
                </div>
            </div>
        )}

        {step === 3 && (
            <div className="space-y-4">
                <h3 className="font-bold text-lg text-slate-dark border-b pb-2">Pasul 3: Setări de Producție</h3>
                
                {/* Primary Settings */}
                <Select 
                    label="Stil Ilustrație" 
                    options={STYLES} 
                    value={selectedStyle} 
                    onChange={(e) => setSelectedStyle(e.target.value as VisualStyle)} 
                />

                <div className="grid grid-cols-2 gap-4">
                    <Select 
                        label="Limbă" 
                        options={LANGUAGES} 
                        value={selectedLanguage} 
                        onChange={(e) => setSelectedLanguage(e.target.value as Language)} 
                    />
                    <Select 
                        label="Format" 
                        options={FORMATS} 
                        value={selectedFormat} 
                        onChange={(e) => setSelectedFormat(e.target.value as AspectRatio)} 
                    />
                </div>

                <div className="grid grid-cols-2 gap-4">
                    <Select 
                        label="Complexitate" 
                        options={COMPLEXITIES} 
                        value={selectedComplexity} 
                        onChange={(e) => setSelectedComplexity(e.target.value as Complexity)} 
                    />
                    <Select 
                        label="Densitate Text" 
                        options={TEXT_DENSITIES} 
                        value={selectedTextDensity} 
                        onChange={(e) => setSelectedTextDensity(e.target.value as TextDensity)} 
                    />
                </div>
                
                <Select 
                    label="Nivel Căutare (Research)" 
                    options={SEARCH_DEPTHS} 
                    value={selectedSearchDepth} 
                    onChange={(e) => setSelectedSearchDepth(e.target.value as SearchDepth)} 
                />
                
                <div className="p-4 bg-blue-50 rounded-lg border border-blue-100 text-sm text-slate-700 mt-2">
                    <p className="font-bold mb-1">Flux de Producție:</p>
                    <ul className="list-disc pl-4 space-y-1">
                        <li>Un nou proiect va fi creat în limba <strong>{selectedLanguage}</strong>.</li>
                        <li>Coperta și Fișa de Personaj (1.5) vor fi generate primele.</li>
                        <li>Paginile vor folosi stilul <strong>{selectedStyle}</strong>.</li>
                    </ul>
                </div>

                <div className="flex justify-between pt-4">
                    <Button variant="secondary" onClick={() => setStep(2)}>&larr; Înapoi</Button>
                    <Button onClick={handleFinish}>✨ Creează Proiect Carte</Button>
                </div>
            </div>
        )}

      </Card>
    </div>
  );
};
